In [2]:
from zmq.decorators import context
!pip install -q -U google-genai faiss-cpu sentence-transformers pandas

# Imports
import pandas as pd
import numpy as np
import faiss
from sentence_transformers import SentenceTransformer
from google import genai
import re
from datetime import datetime, timedelta

In [22]:
Key = "AIzaSyDQ0S8anqLotDjxKcdLpnDeDAMNTbyEHT0"
from google import genai
def geminiGen(Command):
        client = genai.Client(api_key= Key)
        response = client.models.generate_content(
            model="gemini-2.0-flash", contents=Command
        )
        n = response
        return n

def geminiEmbedding(Task):
        client = genai.Client(api_key=Key)

        result = client.models.embed_content(
                model="gemini-embedding-exp-03-07",
                contents=Task)
        r = result.embeddings
        return r
def gemtextgenforstraightapicall(Task):
        client = genai.Client(api_key=Key)
        response = client.models.generate_content(
            model = "gemini-2.0-flash", contents = Task
        )
        n = response
        return n.text

In [4]:
from langchain_google_genai import ChatGoogleGenerativeAI

In [5]:
path1 = "C:\\Python\\GenAiGemini\\accidentReportduetoPotholes.csv"
path2  = "C:\\Python\\GenAiGemini\\SampleDatasetPotholes.csv"

In [24]:
import pandas as pd
ACC = pd.read_csv(path1)
ACC

,Sl. No.,State/UT,2020 - Number of Accidents,2020 - Number of Fatalities,2021 - Number of Accidents,2021 - Number of Fatalities,2022 - Number of Accidents,2022 - Number of Fatalities
0,1,Andhra Pradesh,0.0,0.0,0,0,0,0
1,2,Arunachal Pradesh,13.0,8.0,25,13,20,15
2,3,Assam,194.0,57.0,187,55,319,117
3,4,Bihar,0.0,0.0,0,0,0,0
4,5,Chhattisgarh,5.0,1.0,15,4,40,7
5,6,Goa,0.0,0.0,0,0,0,0
6,7,Gujarat,6.0,6.0,8,5,0,0
7,8,Haryana,183.0,69.0,102,38,130,47
8,9,Himachal Pradesh,0.0,0.0,20,11,2,2
9,10,Jharkhand,129.0,79.0,97,77,56,34
10,11,Karnataka,36.0,7.0,67,16,55,19
11,12,Kerala,25.0,2.0,16,6,25,1
12,13,Madhya Pradesh,439.0,96.0,711,220,759,199
13,14,Maharashtra,61.0,39.0,33,14,4,4
14,15,Manipur,2.0,1.0,6,0,5,3
15,16,Meghalaya,0.0,0.0,0,0,1,0
16,17,Mizoram,1.0,1.0,0,0,2,2
17,18,Nagaland,57.0,2.0,15,3,12,1
18,19,Odisha,174.0,80.0,213,93,158,69
19,20,Punjab,102.0,78.0,114,77,84,60
20,21,Rajasthan,120.0,50.0,69,23,98,51
21,22,Sikkim,0.0,0.0,0,0,1,0
22,23,Tamil Nadu,385.0,46.0,459,109,446,107
23,24,Telangana,58.0,36.0,87,29,153,40
24,25,Tripura,0.0,0.0,0,0,1,1
25,26,Uttarakhand,4.0,1.0,0,0,0,0
26,27,Uttar Pradesh,1447.0,759.0,1254,649,1986,1030
27,28,West Bengal,63.0,39.0,64,28,44,34
28,29,Andaman and Nicobar Islands,0.0,0.0,0,0,0,0
29,30,Chandigarh,0.0,0.0,0,0,1,1
30,31,Jammu and Kashmir,4.0,0.0,4,0,7,0
31,32,Ladakh,NaN,NaN,0,0,0,0
32,33,Dadra and Nagar Haveli and Daman and Diu,1.0,1.0,2,2,7,4
33,34,Delhi,55.0,13.0,56,9,28,7
34,35,Lakshadweep,0.0,0.0,0,0,0,0
35,36,Puducherry,0.0,0.0,1,0,2,1
36,Total,Total,3564.0,1471.0,3625,1481,4446,1856

In [7]:
Potholes = pd.read_csv(path2)

In [31]:
ACC['text_representation'] = ACC['State/UT']  + " " + ACC['2020 - Number of Accidents'].astype(str) + " " + ACC['2021 - Number of Accidents'].astype(str) + " " + ACC['2022 - Number of Accidents'].astype(str)

In [8]:
# Combine columns into a single text representation
Potholes['text_representation'] = Potholes['Location'] + " " + Potholes['Severity'] + " " + Potholes['Description']

# Check the result
print(Potholes['text_representation'][0])  # This will print the combined text for the first complaint

Andheri Medium Pothole with water accumulation

In [34]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
embeddings = model.encode(Potholes['text_representation'])   #embedding for potholes dataset
embeddings1 = model.encode(ACC['text_representation'])  #embeddings for Accidents dataset

In [37]:
print(embeddings)
print(embeddings1)

[[ 0.0002113   0.06797954  0.0430091  ...  0.07140218  0.07192936
  -0.01276356]
 [ 0.03586864  0.04375713  0.0607585  ...  0.00065428  0.00367799
  -0.00845335]
 [ 0.00714575  0.09669092  0.04162277 ...  0.05675502  0.04723298
  -0.03380032]
 ...
 [ 0.01288343  0.04124295  0.09166033 ...  0.04234674 -0.00785293
  -0.0077725 ]
 [ 0.04181498  0.02047975  0.01454877 ...  0.01441803  0.07202748
   0.04685482]
 [ 0.02496247  0.09972118  0.07910664 ...  0.06550261  0.02270672
   0.02559193]]
[[ 0.02508027  0.00165575 -0.05590417 ... -0.02880303 -0.03806801
  -0.00081476]
 [ 0.01912415  0.06444709 -0.03707677 ... -0.00632312  0.01678584
   0.02152348]
 [-0.05395033  0.03941534 -0.05279488 ...  0.01819264 -0.09935827
  -0.06636178]
 ...
 [-0.00102148  0.03245342 -0.01057605 ... -0.01056399 -0.06584032
   0.04576132]
 [-0.01869983 -0.0088687  -0.06843101 ... -0.01950222  0.00695903
   0.07297391]
 [ 0.00979452 -0.01825761 -0.07758874 ... -0.09299901 -0.00823528
  -0.05688682]]

In [11]:
import faiss
import numpy as np

# Convert to float32 if needed
embedding_dim = embeddings.shape[1]
embeddings_np = np.array(embeddings).astype("float32")

# Create FAISS index for complain dataset
index = faiss.IndexFlatL2(embedding_dim)
index.add(embeddings_np)

In [38]:
embeddings1_dim = embeddings1.shape[1]
embeddings1_np = np.array(embeddings1).astype("float32")

# Create FAISS index for ACC dataset
index = faiss.IndexFlatL2(embeddings1_dim)
index.add(embeddings1_np)

In [39]:
texts = Potholes['text_representation'].tolist()
texts1 = ACC['text_representation'].tolist()

In [54]:
import re
from datetime import timedelta, datetime

# Add date column and monthly stats
Potholes['Reported Date'] = pd.to_datetime(Potholes['Reported Date'])
monthly_complaints = Potholes.groupby(Potholes['Reported Date'].dt.to_period("M")).size()
average_complaints = monthly_complaints.mean()

# Helper to extract year-month from question
def extract_month_year(query):
    months = {
        "january": "01", "february": "02", "march": "03", "april": "04",
        "may": "05", "june": "06", "july": "07", "august": "08",
        "september": "09", "october": "10", "november": "11", "december": "12"
    }
    query = query.lower()

    if "last month" in query:
        last_month = (datetime.today().replace(day=1) - timedelta(days=1)).strftime("%Y-%m")
        return last_month
    elif "this month" in query:
        return datetime.today().strftime("%Y-%m")
    elif "this year" in query:
        return datetime.today().strftime("%Y")

    for m in months:
        if m in query:
            match = re.search(r"(20\d{2})", query)
            year = match.group(1) if match else "2025"
            return f"{year}-{months[m]}"
    return None

In [55]:


def ask_question(query, k=3):
    query_embedding = model.encode(query, normalize_embeddings=True).astype("float32")
    _, I = index.search(np.array([query_embedding]), k)
    context_chunks = [texts[i] for i in I[0]]
    context = "\n\n".join(context_chunks)

    month_str = extract_month_year(query)
    if month_str and len(month_str) == 7:
        complaints = monthly_complaints.get(month_str, 0)
        context += f"\n\nIn {month_str}, there were {complaints} pothole complaints."
        context += f" The average number of complaints per month is {average_complaints:.1f}."
    elif month_str and len(month_str) == 4:
        year = int(month_str)
        year_complaints = Potholes[Potholes['Reported Date'].dt.year == year].shape[0]
        context += f"\n\nIn {year}, there were {year_complaints} pothole complaints."

In [56]:
# Convert 'Reported Date' to datetime
Potholes['Reported Date'] = pd.to_datetime(Potholes['Reported Date'])

# Group by month & count complaints
monthly_complaints = Potholes.groupby(Potholes['Reported Date'].dt.to_period("M")).size()

# Optionally, get average per month
average_complaints = monthly_complaints.mean()

print("Monthly complaint counts:\n", monthly_complaints)
print("Average complaints per month:", average_complaints)

Monthly complaint counts:
 Reported Date
2024-01     18
2024-02     14
2024-03     15
2024-04     27
2024-05     28
2024-06     28
2024-07     23
2024-08     18
2024-09     20
2024-10     24
2024-11     22
2024-12     26
2025-01     29
2025-02     16
2025-03     17
2025-04    175
Freq: M, dtype: int64
Average complaints per month: 31.25

In [57]:

# Add date column and monthly stats
Potholes['Reported Date'] = pd.to_datetime(Potholes['Reported Date'])
monthly_complaints = Potholes.groupby(Potholes['Reported Date'].dt.to_period("M")).size()
average_complaints = monthly_complaints.mean()

# Helper to extract year-month from question
def extract_month_year(query):
    months = {
        "january": "01", "february": "02", "march": "03", "april": "04",
        "may": "05", "june": "06", "july": "07", "august": "08",
        "september": "09", "october": "10", "november": "11", "december": "12"
    }
    query = query.lower()

    if "last month" in query:
        last_month = (datetime.today().replace(day=1) - timedelta(days=1)).strftime("%Y-%m")
        return last_month
    elif "this month" in query:
        return datetime.today().strftime("%Y-%m")
    elif "this year" in query:
        return datetime.today().strftime("%Y")

    for m in months:
        if m in query:
            match = re.search(r"(20\d{2})", query)
            year = match.group(1) if match else "2025"
            return f"{year}-{months[m]}"
    return None

# ENHANCED: Handle monthly stats naturally in queries
def ask_question(query, k=3):
    query_embedding = model.encode(query, normalize_embeddings=True).astype("float32")
    _, I = index.search(np.array([query_embedding]), k)
    context_chunks = [texts[i] for i in I[0]]
    context = "\n\n".join(context_chunks)

    month_str = extract_month_year(query)
    if month_str and len(month_str) == 7:
        complaints = monthly_complaints.get(month_str, 0)
        context += f"\n\nIn {month_str}, there were {complaints} pothole complaints."
        context += f" The average number of complaints per month is {average_complaints:.1f}."
    elif month_str and len(month_str) == 4:
        year = int(month_str)
        year_complaints = Potholes[Potholes['Reported Date'].dt.year == year].shape[0]
        context += f"\n\nIn {year}, there were {year_complaints} pothole complaints."

    prompt = f"Context:\n{context}\n\nQuestion: {query}"
    answer = geminiGen(prompt).text
    print(f"Answer: {answer}")
    return answer

In [58]:
response = "What is the number of potholes in april 2025"
print(ask_question(response))

Answer: The provided context states that there were 175 pothole *complaints* in April 2025. It does *not* directly state there were 175 potholes. It's possible some complaints refer to the same pothole, or that some complaints are inaccurate.

Therefore, the best answer, based on the provided information, is: **175 (complaints)**. We cannot definitively say the number of actual potholes.

The provided context states that there were 175 pothole *complaints* in April 2025. It does *not* directly state there were 175 potholes. It's possible some complaints refer to the same pothole, or that some complaints are inaccurate.

Therefore, the best answer, based on the provided information, is: **175 (complaints)**. We cannot definitively say the number of actual potholes.

In [59]:
h="what andheri road"
print(gemtextgenforstraightapicall(h))

Andheri Road is a major road in the Andheri suburb of Mumbai, India. It's actually comprised of two main sections:

*   **Andheri-Kurla Road:** This is a busy east-west road connecting Andheri (West) to Kurla (East). It's a major commercial and residential artery.

*   **Swami Vivekananda Road (S.V. Road):** While often referred to as Andheri Road (especially the stretch that runs through Andheri), this is the main north-south road running through Andheri and connecting it to other suburbs like Bandra, Santacruz, and Borivali.

**Key Characteristics of Andheri Road (both sections):**

*   **Commercial Hub:** Both sections are lined with shops, businesses, restaurants, offices, malls, and other commercial establishments.
*   **Residential Areas:** The road passes through densely populated residential areas.
*   **Traffic:** It's known for heavy traffic congestion, especially during peak hours.
*   **Connectivity:** It's a crucial link connecting different parts of Mumbai. Andheri station on the Western Line is a major railway hub that is very close to S.V Road. The Airport is easily accesible from Andheri-Kurla road.
*   **Landmarks:** Many notable landmarks and businesses are located along or near Andheri Road.
*   **Accessibility:** It's well-connected by public transportation, including buses, taxis, and auto-rickshaws.

In short, Andheri Road is a vital and bustling road in Mumbai, known for its commercial activity, residential areas, and traffic. It plays a significant role in the city's transportation network.

In [42]:
index1 = faiss.IndexFlatL2(embeddings1.shape[1])
index1.add(np.array(embeddings1).astype("float32"))

In [43]:
def ask_question_accidents(query, k=3):
    query_embedding = model.encode(query, normalize_embeddings=True).astype("float32")
    _, I = index1.search(np.array([query_embedding]), k)
    context_chunks = [texts1[i] for i in I[0]]
    context = "\n\n".join(context_chunks)

    prompt = f"Context:\n{context}\n\nQuestion: {query}"
    answer = geminiGen(prompt).text
    print(f"Answer: {answer}")
    return answer

In [44]:
quer = "no accidents in andhra pradesh"
print(ask_question_accidents(quer))

Answer: Based on the provided data, the statement "no accidents in Andhra Pradesh" is **True**. The data shows 0.0 accidents, 0 deaths, and 0 injuries for Andhra Pradesh.

Based on the provided data, the statement "no accidents in Andhra Pradesh" is **True**. The data shows 0.0 accidents, 0 deaths, and 0 injuries for Andhra Pradesh.